# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThorChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThorChat
  
  #  for Api Intigration
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'Toast-Swift'
  pod 'SwiftyJSON'
  
  # Key board Handle
  pod 'IQKeyboardManager'
  
  # Image Loader
  pod 'SDWebImage'
  
  #Country Picker
  pod 'CountryPickerView'
  
  
  # Firebase Init
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Firestore'
  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'
  
  

  target 'ThorChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThorChatUITests' do
    # Pods for testing
  end

end
